name: Build and Deploy

on:
  push:
    branches: [main]
  schedule:
    # 毎時0分に実行
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    env:
      TZ: Asia/Tokyo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: |
          touch .env
          echo "OWM_API_KEY=$OWM_API_KEY" >> .env
          echo "OWM_LAT=$OWM_LAT" >> .env
          echo "OWM_LON=$OWM_LON" >> .env

          npm run build
        env:
          NODE_ENV: production
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          OWM_LAT: ${{ vars.OWM_LAT }}
          OWM_LON: ${{ vars.OWM_LON }}

      - name: Remove Unnecessary File
        run: rm -f ./dist/mockServiceWorker.js

      - name: 🌎 Install Playwright browsers
        # PlaywrightでChromiumを使うためのバイナリをインストール
        run: npx playwright install chromium

      - name: Start Web App server in background
        run: npx serve -s ./dist -l 3000 &

      - name: ⏳ Wait for server to start
        # サーバー起動に必要な時間だけ待機
        run: sleep 5

      - name: Take Screenshot using TypeScript
        run: |
          npm run screenshot
          # スクリーンショットを dist ディレクトリに移動
          mv screenshot.jpg ./dist/screenshot.jpg

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          # distディレクトリには、ビルド成果物と新しく撮影された screenshot.jpg を含む
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
